title: "Kris Hollingsworth, PhD"
description: "Accessibility doesn't need to look boring."

url: "https://DoctorHaitch.github.io"
# url: "http://192.168.1.159:4000"
baseurl: ""

github:
  is_project_page: false

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-sitemap

pagination:
  enabled: true
  collection: 'posts'
  per_page: 5
  permalink: '/page:num/'
  filter: 'pinned == false'
  # Auto-page generation

autopages:
  enabled: true
#    categories:
#      permalink: '/category/:tag/'
  tags:
    layouts:
      - autopage_tags.html
    title: 'Posts tagged with ":tag"'
    permalink: '/tag/:tag/'
  collections:
    enabled: false
  categories:
    enabled: false


defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      mathjax: true
      layout: main
      profile: false

  - scope:
      path: ""
      type: "posts"
    values:
      mathjax: true
      layout: main
      profile: false