title: Kris Hollingsworth, PhD
description: Accessibility doesn't need to look boring.

github:
  is_project_page: false

paginate: 5          # posts per page (change as you like)
paginate_path: "/blog/page:num/"