- organization: "Mathematical Association of America, North Central Section"
  role: "Member at Large"
  start: "2026-07-01"
  end: "2028-06-30"
  responsibilities: "Serve as a member of the executive committee, participate in decision-making, and contribute to the planning and execution of section activities and initiatives."

- organization: "MathHappens Foundation"
  role: "Mankato, MN Site Coordinator"
  start: "2023-09-15"
  end: "2026-10-15"
  responsibilities: 
    - "Hire and train new MathHappens facilitators from the MNSU-Mankato student population to engage the public in high-quality, hands-on mathematics activities."
    - "Coordinate between the MathHappens Foundation and the Children's Museum of Southern Minnesota to ensure smooth operation of the MathRoom."
    - "Design and collect new activities for the MathRoom."
  outcome: "Created a successful, self-sustaining MathRoom at the Children's Museum of Southern Minnesota, providing engaging mathematical experiences for children and families. It is now being run by MNSU students independently."

- organization: "University of Delaware, Department of Mathematics"
  role: "Summer Speaker Series Organizer"
  start: "2016-04-20"
  end: "2016-08-12"
  advisor: "Dr. Francisco-Javier Sayas"
  responsibilities:
    - "Organize and coordinate a series of summer talks by both faculty and student researchers in the Department of Mathematics."
    - "Assist in organizing Summer Research Symposium, including scheduling, logistics, and promotion of the event."

- organization: "University of Delaware, Department of Mathematics"
  role: "RAMP (Review of Advanced Mathematical Problems) Teaching Assistant"
  start: "2019-07-22"
  end: "2019-08-15"
  advisor: "Dr. Chad Giusti"
  responsibilities:
    - "Assist running on-campus orientation and review program specifically designed to help incoming Mathematics and Applied Mathematics graduate students review key academic materials before starting their first-year coursework."
    - "Specifically support students in key concepts from Linear Algebra."